// Pure helpers shared by the reducer and the timer tick loop.
// See specs/04-in-game-behavior.md §"Timer tick model".

import type { SseEvent } from "@/shared/events";
import type { EpochMs, GameState } from "@/shared/types";

import { reconcileAlertOnChange } from "./alerts";

/**
 * Commit elapsed time to the active player's remainingMs. Idempotent for
 * non-Running phases or when lastTickAt is null. Returns the new state, any
 * alert SSE events generated by zero-crossing, and the new lastTickAt.
 */
export function commitElapsed(
  state: GameState,
  now: EpochMs,
  lastTickAt: EpochMs | null,
): { state: GameState; events: SseEvent[]; lastTickAt: EpochMs | null } {
  if (
    state.phase !== "Running" ||
    lastTickAt == null ||
    state.config == null ||
    state.currentPlayerIdx == null
  ) {
    return { state, events: [], lastTickAt };
  }
  const delta = now - lastTickAt;
  if (delta <= 0) {
    return { state, events: [], lastTickAt: now };
  }
  const activeId = state.currentOrder[state.currentPlayerIdx];
  if (activeId === undefined) {
    return { state, events: [], lastTickAt: now };
  }
  const prevMs = state.remainingMs[activeId] ?? 0;
  const newMs = prevMs - delta;
  const remainingMs = { ...state.remainingMs, [activeId]: newMs };
  let s2: GameState = { ...state, remainingMs };
  const { state: s3, events } = reconcileAlertOnChange(
    s2,
    activeId,
    prevMs,
    newMs,
    state.config.mode,
    now,
  );
  s2 = s3;
  return { state: s2, events, lastTickAt: now };
}
